# Generated by Django 2.2.24 on 2021-11-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=120)),
                ('Email_Id', models.EmailField(max_length=12000)),
                ('Batch', models.CharField(max_length=12)),
                ('Username', models.CharField(max_length=120)),
                ('Password', models.CharField(max_length=120)),
            ],
        ),
    ]
