# Generated by Django 2.2.24 on 2021-11-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_projectinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinput',
            name='project_name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
