# Generated by Django 2.2.24 on 2021-11-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_projectinput_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinput',
            name='project_name',
            field=models.CharField(max_length=30),
        ),
    ]
