# Generated by Django 2.2.24 on 2021-12-01 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_interviewinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinput',
            name='project_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
