# Generated by Django 2.2.24 on 2021-12-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_projectinput_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinput',
            name='project_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
