# Generated by Django 2.2.24 on 2021-12-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20211201_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinput',
            name='project_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
