# Generated by Django 2.2.24 on 2021-12-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20211201_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinput',
            name='project_image',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
    ]
