# Generated by Django 2.2.24 on 2021-12-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20211202_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Username',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
