# Generated by Django 2.2.24 on 2021-12-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_contact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinput',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
