# Generated by Django 2.2.24 on 2021-12-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20211202_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewinput',
            name='interview_category',
            field=models.CharField(default='Others', max_length=120),
        ),
        migrations.AddField(
            model_name='projectinput',
            name='project_category',
            field=models.CharField(default='Others', max_length=120),
        ),
        migrations.AlterField(
            model_name='interviewinput',
            name='interview_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
